name: Validate Conjur Policies

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  validate-conjur-policies:
    name: Validate Conjur Policies
    runs-on: self-hosted
    
    # Set the permissions needed for OIDC authentication
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to detect changes between branches

      - name: Validate Conjur Policy Files
        uses: szh/conjur-policy-whisperer@main
        with:
          conjur_url: ${{ secrets.CONJUR_URL }}
          conjur_account: ${{ secrets.CONJUR_ACCOUNT }}
          conjur_jwt_service_id: github
          policy_dir: './policies'  # Adjust to your policy directory
